# Generated by Django 6.0 on 2026-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
