# Generated by Django 6.0 on 2026-01-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_todo_due_time_todo_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
